# Generated by Django 3.2.6 on 2021-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.CharField(default='Describe yourself', max_length=200),
            preserve_default=False,
        ),
    ]
