# Generated by Django 3.2.6 on 2021-08-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater_api', '0002_player_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
    ]
