# Generated by Django 3.2.6 on 2021-08-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater_api', '0003_remove_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rater_api.category'),
            preserve_default=False,
        ),
    ]
