# Generated by Django 3.2.6 on 2021-08-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater_api', '0004_game_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_category',
            new_name='category',
        ),
    ]
