# Generated by Django 3.2.6 on 2021-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater_api', '0005_rename_game_category_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
